Repository IBM/crossplane-provider-ibm-cloud, pull requests merged in 2022-01, with the labels that each got.

#6 CatalogSource building script
  .github/workflows/catsrc.yaml
  .gitignore
  common/scripts/build_catsrc.sh
  common/scripts/install_tools.sh
Labels: size/XL

#7 Fix files due to certification
  bundle.Dockerfile
  bundle/manifests/crossplane-provider-ibm-cloud-operator.clusterserviceversion.yaml
  bundle/metadata/annotations.yaml
  common/scripts/adjust_manifests.sh
  config/manifests/bases/crossplane-provider-ibm-cloud-operator.clusterserviceversion.yaml
Labels: size/XL

#8 Fix buildx download target
  Makefile
Labels: size/XS

#9 Fix strange named roles and bindings
  .github/workflows/ci.yml
  bundle/manifests/ibm-crossplane-provider-ibm-cloud-ibm-crossplane_rbac.authorization.k8s.io_v1_clusterrole.yaml
  bundle/manifests/ibm-crossplane-provider-ibm-cloud-ibm-crossplane_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
  bundle/manifests/ibm-crossplane-provider-kubernetes-ibm-crossplane-provider-ibm-cloud_rbac.authorization.k8s.io_v1_clusterrole.yaml
  common/scripts/build_catsrc.sh
  config/rbac/clusterrole_binding.yaml
  config/rbac/ibm-crossplane_clusterrole.yaml
  config/rbac/ibm-crossplane_clusterrole_binding.yaml
  config/rbac/kustomization.yaml
Labels: size/L

#10 change project name
  PROJECT
  bundle.Dockerfile
  bundle/manifests/ibm-crossplane-provider-ibm-cloud-operator.clusterserviceversion.yaml
  bundle/metadata/annotations.yaml
  cluster/images/provider-ibm-cloud-controller/Makefile
  cluster/local/integration_tests.sh
  common/Makefile.operator.mk
  common/scripts/adjust_manifests.sh
  common/scripts/build_catsrc.sh
  common/scripts/lint-csv.sh
  config/manager/manager.yaml
  config/manifests/bases/ibm-crossplane-provider-ibm-cloud-operator.clusterserviceversion.yaml
  ibm/Makefile.common.mk
  package/crossplane.yaml
Labels: size/M

#11 Fix dockerfile
  cluster/images/provider-ibm-cloud/Dockerfile
Labels: size/XS

#12 fix package names in build_catsrc.sh
  common/scripts/build_catsrc.sh
Labels: size/XS

#14 IKS installation script
  hack/install-provider.sh
Labels: size/M

#15 Fix IKS installation script
  hack/install_provider.sh
Labels: size/M

#17 add annotation to hide operator
  bundle/manifests/ibm-crossplane-provider-ibm-cloud-operator.clusterserviceversion.yaml
  config/manifests/bases/ibm-crossplane-provider-ibm-cloud-operator.clusterserviceversion.yaml
Labels: size/XS

#19 yq4 support for installation script
  hack/install-provider.sh
  hack/install_provider.sh
Labels: size/L

#21 Copyright date update
  .github/workflows/catsrc.yaml
  Makefile
  common/Makefile.common.mk
  common/Makefile.operator.mk
  common/scripts/adjust_manifests.sh
  common/scripts/build_catsrc.sh
  common/scripts/config_docker.sh
  common/scripts/install-operator-sdk.sh
  common/scripts/install_tools.sh
  common/scripts/lint-csv.sh
  common/scripts/lint_copyright_banner.sh
  common/scripts/update_catalogsource.sh
  common/scripts/update_global_pull_secrets.sh
  hack/install_provider.sh
  ibm/Makefile.common.mk
Labels: size/M

#20 Fix jwt-go vulnerability
  common/scripts/build_catsrc.sh
  go.mod
  go.sum
Labels: size/S
