Repository IBM/crossplane-provider-ibm-cloud, pull requests merged in 2022-02, with the labels that each got.

#23 Update release version
  PREVIOUS_VERSION
  RELEASE_VERSION
  bundle/manifests/ibm-crossplane-provider-ibm-cloud-operator.clusterserviceversion.yaml
  config/manager/manager.yaml
  config/manifests/bases/ibm-crossplane-provider-ibm-cloud-operator.clusterserviceversion.yaml
Labels: size/S

#24 Update release version
  PREVIOUS_VERSION
  RELEASE_VERSION
  bundle/manifests/ibm-crossplane-provider-ibm-cloud-operator.clusterserviceversion.yaml
  config/manager/manager.yaml
  config/manifests/bases/ibm-crossplane-provider-ibm-cloud-operator.clusterserviceversion.yaml
Labels: size/S, lgtm

#26 update go to 1.17.7
  .github/workflows/catsrc.yaml
Labels: size/XS, lgtm
